### ISSUE TITLE
Exception: Lark constructor uses `standard` setting, should be using `basic`

### ISSUE THREAD

**Issue by Pet3ris** [starkware-libs/cairo-lang#75]
Hi There, this line of code is using a Lark lexer setting of "standard":

https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/compiler/parser.py#L33

Which seems to be different than what Lark expects:

https://github.com/lark-parser/lark/blob/master/lark/lark.py#L360

Been hit by this exception when switching across to `0.9.0`.

**Comment by LouisDelbosc** [comment]
I also have this error and would like to know how to solve it.

**Comment by Pet3ris** [comment]
The work around is to reinstall the underlying lark-parser dependency, but I’m not sure why that works given the above mismatch.

**Comment by LouisDelbosc** [comment]
Did you uninstall and reinstall lark-parser without any other instructions and it worked ? 😲

**Comment by Pet3ris** [comment]
@LouisDelbosc yes. Lots of people have used this approach in the past :).

**Comment by ca11ab1e** [comment]
It's because cairo-lang is using https://pypi.org/project/lark-parser but some other project install https://pypi.org/project/lark.

`lark-parser` seems to be replace with `lark`, and currently we can't use https://github.com/crytic/amarna in the same devenv as cairo-lang because it will be impossible to run any cairo commands ...

**Comment by RaitoBezarius** [comment]
I just encountered this issue, I will try to send a PR to use `lark` now in the project and fix whatever breakage happened meanwhile.
